
        
            <div class="fc-lst-sc">
                <ul class="social-media-logo">
                    <li><a href="https://twitter.com/TheBodyShopSE?s=09" target="_blank"><i class="fab fa-twitter"></i></a></li>
                    <li><a href="https://instagram.com/thebodyshopsaudieast" target="_blank"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="https://www.facebook.com/thebodyshopSaudiEast/" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                    <li><a href="https://www.youtube.com/user/thebodyshop" target="_blank"><i class="fab fa-youtube"></i></a></li>
                    <li><a href="https://www.snapchat.com/add/thebodyshopruh" target="_blank"><i class="fab fa-snapchat-ghost"></i></a></li>
                </ul>
            </div>
