<div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="ft-contact">
                <h3>Here to help</i></h3>
                <ul>
                    <li>You can contact us via Email:</li>
                    <li><a href="mailto:support@thebodyshopeast.com" title="" target="_blank"> support@thebodyshopeast.com </a></li>
                    <li><a href="#" id="widget-live-chat" title=""> Live chat </a></li>
                    <li>SUN TO THU: 9AM TO 5PM</li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3  col-sm-6 col-xs-12">
            <div class="ft-info">
                <h3>userful infomation</i></h3>
                <ul>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/delivery-information-and-return-policy/">Delivery Information and Return Policy</a></li>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/termsconditions/">Terms And Conditions</a></li>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/termsconditions/services/privacy-policy-new/">Privacy Notice</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3  col-sm-6 col-xs-12">
            <div class="ft-wts">
                <h3>Site</h3>
                <ul>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/sitemap/">Sitemap</a></li>
                </ul>
            </div>
        </div>
        <div class="col-lg-3 col-sm-6 col-xs-12">
            <div class="ft-about">
                <h3>about us</h3>
                <ul>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/about-us/">Who We Are</a></li>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/plastics-for-change/">Plastics</a></li>
                    <li><a href="https://www.thebodyshop.com.sa/east/en/forever-against-animal-testing/">Against Animal Testing</a></li>
                    <li><a href="/east/en/natura-and-co">Natura &amp; Co</a></li>
                    <li><a href="/east/en/ingredients">Ingredients Hub</a></li>
                </ul>
            </div>
        </div>