<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Snaptec\Fastbuy\Block\Index
 */

// phpcs:disable Generic.Files.LineLength.TooLong


?>
<div class="main-content">

    <div class="row">
        <div class="interior">
            <button type="button" class="btn btn-primary">
                <a class="btn" href="#open-modal"> Add Product</a>
            </button>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <form>
                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
                </div>
                <label for="fname">First Name</label>
                <input type="text" id="fname" name="firstname" placeholder="Your name..">

                <label for="lname">Last Name</label>
                <input type="text" id="lname" name="lastname" placeholder="Your last name..">

                <label for="lname">Address</label>
                <input type="text" id="address" name="address" placeholder="Your address..">

                <button id="btn-submit" type="submit" class="btn btn-primary">Submit</button>
                <div id="parent">
                </div>
            </form>
        </div>
        <div class="col-lg-6">
            
            <div id="shipping-method" class="col-lg-12">
                <div class="col-lg-12">
                    <div class="title-shipping-method">Shipping Methods</div>
                </div>
                <label class="shipping-method">Flat Rate
                    <input type="radio" checked="checked" name="radio" value="flatrate_flatrate">
                    <span class="checkmark"></span>
                </label>
                <label class="shipping-method">Cash on Delivery
                    <input type="radio" name="radio" value="cashondelivery">
                    <span class="checkmark"></span>
                </label>
            </div>

            <div id="payment-method" class="col-lg-12">
                <div class="col-lg-12">
                    <div class="title-shipping-method">Payment Methods</div>
                </div>
                <label class="payment-method">Check Money
                    <input type="radio" checked="checked" name="payment" value="checkmo">
                    <span class="checkmark_payment"></span>
                </label>
                <label class="payment-method">Cash on Delivery
                    <input type="radio" name="payment" value="cashondelivery">
                    <span class="checkmark_payment"></span>
                </label>
            </div>

        </div>

    </div>
</div>

<div id="open-modal" class="modal-window">
    <div>
        <h1>Add Product Modal</h1>
        <a href="#" title="Close" class="modal-close">Close</a>
        <form class="add-product-modal">
            <label for="lname" class="lname">Product</label>
            <select id="nameProduct">
                <?php
                foreach ($block->getAllProduct() as $product) {
                    echo '<option value=' . $product->getId() . '>' . $product->getName() . '</option>';
                }
                ?>
            </select>
            <label for="lname" class="qtyTitle">Quantity</label>
            <input type="number" id="qtyProduct" name="quantity" />
            <input type="hidden" name="url-add-to-cart" value="<?= $block->getUrl('checkout/cart/add') ?>">
            <button id="btn-add-to-cart" class="add-to-cart">Add To Cart</button>
        </form>
    </div>
</div>

<script>
    require([
        "jquery",
    ], function($) {
        "use strict";
        $('button.add-to-cart').click(function(e) {
            e.preventDefault();
            let nameProduct = $('#nameProduct').val();
            console.log(nameProduct);
            let quantityProduct = $('#qtyProduct').val();
            $('#parent').append(
                '<div class="alert alert-success d-flex align-items-center" role="alert">' +
                '<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/><path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/></svg>' +
                '<div>' +
                'Adding Product: ' + nameProduct + '. Quantity: ' + quantityProduct + ' Successfull' +
                '</div></div>'

            );
        });

    });
</script>
</div>

