

<script>
require([
    "jquery",
    "owlcarousel"
],
function($,owlcarousel){
              $('#banner-carousel').owlCarousel({
                items:1,
                loop:true,
                margin:10,
                nav:true,
                dots:false,
                autoPlay:1000,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:1
                    },
                    1000:{
                        items:1
                    }
                }
              });  
        
});

</script>